import { addDaysISO, formatMonthDay } from "./schema.js";

const WORKING = [
  {
    className: "AP Calculus AB",
    schedule: "Mon/Wed 4:00–5:30pm CT",
    dayOffset: 25,
    duration: "90 min",
    subject: "Calculus",
    tutorName: "Maya Chen",
    email: "maya.chen@example.com",
    status: "Offer",
    note: "",
  },
  {
    className: "SAT Math Intensive",
    schedule: "Tue/Thu 6:00–7:30pm CT",
    dayOffset: 27,
    duration: "90 min",
    subject: "SAT Math",
    tutorName: "Maya Chen",
    email: "maya.chen@example.com",
    status: "Offer",
    note: "Second section for the same tutor — one combined email.",
  },
  {
    className: "Algebra 2 Honors",
    schedule: "Tue/Thu 3:30–5:00pm CT",
    dayOffset: 40,
    duration: "90 min",
    subject: "Algebra",
    tutorName: "Priya Shah",
    email: "priya.shah@example.com",
    status: "Offer",
    note: "",
  },
  {
    className: "Spanish Conversation",
    schedule: "Tue 5:00–6:00pm CT",
    dayOffset: 35,
    duration: "60 min",
    subject: "Spanish",
    tutorName: "",
    email: "",
    status: "Offer",
    note: "Tutor not chosen yet.",
  },
  {
    className: "AP Biology",
    schedule: "Mon/Wed 5:00–6:30pm CT",
    dayOffset: 19,
    duration: "90 min",
    subject: "Biology",
    tutorName: "Jordan Hale",
    email: "jordan.hale@example.com",
    status: "Accepted",
    note: "Placement still needs to be created.",
  },
  {
    className: "Geometry",
    schedule: "Wed/Fri 4:00–5:00pm CT",
    dayOffset: 12,
    duration: "60 min",
    subject: "Geometry",
    tutorName: "Elena Vasquez",
    email: "elena.vasquez@example.com",
    status: "Accepted",
    note: "",
  },
  {
    className: "AP Literature",
    schedule: "Thu 7:00–8:30pm CT",
    dayOffset: 75,
    duration: "90 min",
    subject: "English",
    tutorName: "Sam Okonkwo",
    email: "sam.okonkwo@example.com",
    status: "Accepted",
    note: "Starts well outside the 30-day window.",
  },
  {
    className: "Chemistry Foundations",
    schedule: "Sat 10:00–11:30am CT",
    dayOffset: 15,
    duration: "90 min",
    subject: "Chemistry",
    tutorName: "Luis Ortega",
    email: "luis.ortega@example.com",
    status: "Not in progress",
    note: "Blocked on an expired live stream ICA.",
  },
  {
    className: "ACT English",
    schedule: "Mon 7:00–8:00pm CT",
    dayOffset: 69,
    duration: "60 min",
    subject: "ACT English",
    tutorName: "Sam Okonkwo",
    email: "sam.okonkwo@example.com",
    status: "Waiting for response",
    note: "Offer already sent.",
  },
  {
    className: "World History",
    schedule: "Fri 3:00–4:00pm CT",
    dayOffset: 18,
    duration: "60 min",
    subject: "History",
    tutorName: "Alex Kim",
    email: "alex.kim@example.com",
    status: "Declined",
    note: "",
  },
];

const SUBS = [
  {
    className: "AP US History",
    dayOffset: 9,
    time: "4:00–5:30pm",
    duration: "90 min",
    status: "Available",
    note: "",
  },
  {
    className: "Precalculus",
    dayOffset: 13,
    time: "6:30–7:30pm",
    duration: "60 min",
    status: "Available",
    note: "",
  },
  {
    className: "Physics 1",
    dayOffset: 7,
    time: "3:00–4:30pm",
    duration: "90 min",
    status: "Waiting for response",
    note: "Offered to Alex Kim",
  },
];

const INSTRUCTORS = [
  ["Maya Chen", "maya.chen@example.com", "Calculus; SAT Math", "Active"],
  ["Jordan Hale", "jordan.hale@example.com", "Biology", "Active"],
  ["Priya Shah", "priya.shah@example.com", "Algebra", "Active"],
  ["Luis Ortega", "luis.ortega@example.com", "Chemistry", "Expired"],
  ["Elena Vasquez", "elena.vasquez@example.com", "Geometry", "Active"],
  ["Sam Okonkwo", "sam.okonkwo@example.com", "ACT English; Literature", "Active"],
  ["Alex Kim", "alex.kim@example.com", "US History", "Active"],
  ["Riley Nguyen", "riley.nguyen@example.com", "Physics; Precalculus", "Active"],
];

export function createSeed(now = new Date()) {
  return {
    tabs: {
      Working: {
        headers: [
          "Class Name",
          "Schedule",
          "Start Date",
          "Days Until Start",
          "Duration",
          "Subject",
          "Tutor Name",
          "Tutor Email",
          "Status",
          "Notes",
        ],
        rows: WORKING.map((row) => {
          const start = addDaysISO(now, row.dayOffset);
          return [
            row.className,
            row.schedule,
            start,
            String(row.dayOffset),
            row.duration,
            row.subject,
            row.tutorName,
            row.email,
            row.status,
            row.note,
          ];
        }),
      },
      Subs: {
        headers: ["Class Name", "Date", "Time", "Duration", "Status", "Note"],
        rows: SUBS.map((row) => [
          row.className,
          formatMonthDay(addDaysISO(now, row.dayOffset)),
          row.time,
          row.duration,
          row.status,
          row.note,
        ]),
      },
      Instructors: {
        headers: ["Tutor Name", "Tutor Email", "Subjects", "ICA Status"],
        rows: INSTRUCTORS.map((row) => [...row]),
      },
      "Activity Log": {
        headers: ["Timestamp", "Action", "Status", "Recipient", "Detail", "Error"],
        rows: [],
      },
    },
  };
}
